branches:
  only:
    - master
    - dev

language: node_js
install:
  - yarn install --frozen-lockfile
before_script:
  - yarn run prettier:check
  - yarn run eslint:check
  - yarn run tsc:check
script:
  - yarn test
